# Generated by Django 4.0.2 on 2022-03-21 00:11

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='descripcion',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
