# Generated by Django 4.0.1 on 2022-03-17 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogApp', '0002_categoria_alter_post_options_post_categoria'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='categoria',
        ),
        migrations.AddField(
            model_name='post',
            name='categoria',
            field=models.ManyToManyField(null='True', to='blogApp.Categoria'),
            preserve_default='True',
        ),
    ]
