# Generated by Django 4.0.1 on 2022-03-17 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogApp', '0003_remove_post_categoria_post_categoria'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='categoria',
            new_name='categorias',
        ),
    ]
