# Generated by Django 4.0.2 on 2022-03-21 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('porfolioApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='url',
            new_name='demo_dir',
        ),
        migrations.AddField(
            model_name='project',
            name='git_dir',
            field=models.URLField(blank=True, null=True),
        ),
    ]
