# Generated by Django 4.0.2 on 2022-02-27 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('porfolioApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='imagen',
            field=models.ImageField(upload_to='porfolioApp/image/'),
        ),
    ]
